version: '3.9'
services:
  postgres:
    image: postgres:16.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: people
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5