spring:
    application:
        name: ${rootProject.name}
    datasource:
        url: jdbc:postgresql://localhost:5432/people
        username: admin
        password: admin
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    jackson:
        # Global setting to not return null objects in JSON responses
        default-property-inclusion: NON_NULL
    threads:
        virtual:
            enabled: true

server:
    port: 8080

management:
    server:
        port: 9080
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
            probes:
                enabled: true
    info:
        java.enabled: true
        env.enabled: true

springdoc:
    use-management-port: true

application:
    cors:
        origins: http://localhost:\${management.server.port}

logging:
    level:
        '[org.springframework]': ERROR